import type { TheorySource, TheorySourceId } from "./types";

export const theorySources: Record<TheorySourceId, TheorySource> = {
  "ioai-2026": {
    id: "ioai-2026",
    title: "IOAI 2026 Syllabus",
    authorsOrOwner: "International Olympiad in Artificial Intelligence",
    url: "https://ioai-official.org/wp-content/uploads/2025/10/Syllabus.pdf",
    license: "Nguồn chính thức; chỉ liên kết và diễn giải",
    note: "Dùng để xác định phạm vi và mức Theory, Practice hoặc Both; không dùng làm giáo trình thay thế.",
  },
  "d2l-vi": {
    id: "d2l-vi",
    title: "Đắm mình vào Học Sâu",
    authorsOrOwner: "D2L.ai và cộng đồng bản dịch tiếng Việt",
    url: "https://github.com/d2l-ai/d2l-vi",
    localPath: "/books/dam-minh-vao-hoc-sau-vi.pdf",
    license: "CC BY-SA 4.0; mã mẫu theo giấy phép của dự án",
    note: "Nguồn đọc tiếng Việt cho đại số tensor, tối ưu, mạng nơ-ron, CV, attention và NLP.",
  },
  "d2l-en": {
    id: "d2l-en",
    title: "Dive into Deep Learning",
    authorsOrOwner: "Aston Zhang, Zachary C. Lipton, Mu Li, Alexander J. Smola",
    url: "https://github.com/d2l-ai/d2l-en",
    localPath: "/books/dive-into-deep-learning-en.pdf",
    license: "CC BY-SA 4.0; mã mẫu theo giấy phép của dự án",
    note: "Nguồn tiếng Anh có toán, code và thí nghiệm; ưu tiên khi bản dịch chưa có chương tương ứng.",
  },
  mml: {
    id: "mml",
    title: "Mathematics for Machine Learning",
    authorsOrOwner: "Marc Peter Deisenroth, A. Aldo Faisal, Cheng Soon Ong",
    url: "https://mml-book.github.io/",
    license: "PDF đọc miễn phí từ trang tác giả; chỉ liên kết và diễn giải",
    note: "Nguồn nền tảng về đại số tuyến tính, giải tích, xác suất, tối ưu, hồi quy, PCA và SVM.",
  },
  "pml-intro": {
    id: "pml-intro",
    title: "Probabilistic Machine Learning: An Introduction",
    authorsOrOwner: "Kevin P. Murphy",
    url: "https://probml.github.io/pml-book/book1.html",
    localPath: "/books/probabilistic-machine-learning-introduction.pdf",
    license: "CC BY-NC-ND",
    note: "Nguồn tra cứu ML cổ điển, đánh giá, mô hình xác suất và giảm chiều; không sửa hay cắt ghép PDF.",
  },
  "pml-advanced": {
    id: "pml-advanced",
    title: "Probabilistic Machine Learning: Advanced Topics",
    authorsOrOwner: "Kevin P. Murphy",
    url: "https://probml.github.io/book2",
    license: "CC BY-NC-ND",
    note: "Nguồn nâng cao cho representation learning, mô hình sinh và diffusion; không sửa hay cắt ghép PDF.",
  },
  "vision-book": {
    id: "vision-book",
    title: "Foundations of Computer Vision",
    authorsOrOwner: "Torralba, Isola và Freeman",
    url: "https://visionbook.mit.edu/",
    license: "CC BY-NC-ND",
    note: "Nguồn CV từ biểu diễn ảnh đến CNN, transformer, transfer learning và mô hình sinh.",
  },
  "nlp-principles": {
    id: "nlp-principles",
    title: "Principles of Natural Language Processing",
    authorsOrOwner: "Susan McRoy",
    url: "https://wisconsin.pressbooks.pub/naturallanguage/",
    localPath: "/books/principles-of-natural-language-processing.pdf",
    license: "CC BY-NC 4.0",
    note: "Nguồn nhập môn về dữ liệu ngôn ngữ, biểu diễn, mô hình hóa và đánh giá NLP.",
  },
  "nlp-representation": {
    id: "nlp-representation",
    title: "Representation Learning for Natural Language Processing",
    authorsOrOwner: "Zhiyuan Liu, Yankai Lin, Maosong Sun",
    url: "https://library.oapen.org/handle/20.500.12657/39974",
    license: "CC BY 4.0",
    note: "Nguồn nâng cao về biểu diễn từ, câu, tài liệu và tri thức.",
  },
  "speech-processing": {
    id: "speech-processing",
    title: "Introduction to Speech Processing",
    authorsOrOwner: "Aalto University và nhóm tác giả",
    url: "https://speechprocessingbook.aalto.fi/",
    localPath: "/books/introduction-to-speech-processing.pdf",
    license: "Open access, Creative Commons; xem điều kiện bản phát hành đi kèm",
    note: "Nguồn chính cho sampling, phổ, speech features, ASR, tổng hợp và đánh giá âm thanh.",
  },
  "think-dsp": {
    id: "think-dsp",
    title: "Think DSP: Digital Signal Processing in Python",
    authorsOrOwner: "Allen B. Downey",
    url: "https://greenteapress.com/thinkdsp/thinkdsp.pdf",
    localPath: "/books/think-dsp.pdf",
    license: "CC BY-NC-SA 4.0",
    note: "Nguồn thực hành để hiểu waveform, phổ, sampling, convolution và lọc tín hiệu bằng Python.",
  },
  "hubert-paper": {
    id: "hubert-paper",
    title: "HuBERT: Self-Supervised Speech Representation Learning by Masked Prediction of Hidden Units",
    authorsOrOwner: "Wei-Ning Hsu và cộng sự",
    url: "https://arxiv.org/abs/2106.07447",
    license: "Bài báo nghiên cứu; chỉ liên kết và diễn giải",
    note: "Nguồn gốc cho clustering targets, masked prediction và quy trình pretraining HuBERT.",
  },
  "whisper-paper": {
    id: "whisper-paper",
    title: "Robust Speech Recognition via Large-Scale Weak Supervision",
    authorsOrOwner: "Alec Radford và cộng sự, OpenAI",
    url: "https://cdn.openai.com/papers/whisper.pdf",
    license: "Bài báo chính thức của OpenAI; chỉ liên kết và diễn giải",
    note: "Nguồn gốc cho kiến trúc encoder-decoder, log-mel frontend, task/language/timestamp tokens và đánh giá Whisper.",
  },
  "qwen-audio-official": {
    id: "qwen-audio-official",
    title: "Qwen-Audio official repository and model documentation",
    authorsOrOwner: "QwenLM, Alibaba Cloud",
    url: "https://github.com/QwenLM/Qwen-Audio",
    license: "Giấy phép Qwen đi kèm repository; chỉ liên kết và diễn giải",
    note: "Nguồn model-specific cho processor, prompt markers, kiến trúc và phạm vi nhiệm vụ Qwen-Audio.",
  },
  "voxtral-official": {
    id: "voxtral-official",
    title: "Voxtral Small 25.07 model documentation",
    authorsOrOwner: "Mistral AI",
    url: "https://docs.mistral.ai/models/voxtral-small-25-07",
    license: "Tài liệu model chính thức; open weights Apache 2.0 cho checkpoint được nêu",
    note: "Nguồn model-specific cho audio instruction, transcription, translation và audio understanding; luôn kiểm tra đúng phiên bản.",
  },
};

export function getTheorySources(ids: TheorySourceId[]): TheorySource[] {
  return ids.map((id) => theorySources[id]);
}
