/**
 * Section E — Nền tảng Toán & Tin cho vòng 1, kèm khối AI tạo sinh và đạo đức AI.
 *
 * Vì sao có section này: bảng 60 mục của Syllabus IOAI 2026 không tách riêng đại
 * số tuyến tính, giải tích, xác suất hay ngữ nghĩa Python, nhưng các đề trắc
 * nghiệm vòng 1 đã công bố công khai của những olympiad AI quốc gia lại dành cho
 * các mảng này tỷ trọng lớn nhất. Toàn bộ câu hỏi ở đây là **bản gốc do dự án
 * soạn**, chỉ hiệu chỉnh theo *dạng, chủ đề và mức độ* của các nguồn công khai
 * ghi trong `calibratedFrom`; không có câu nào chép nguyên văn từ đề thi.
 *
 * Phong cách bám đề thật: đề dẫn ngắn, 4 phương án, trả lời nhanh. Đây là khác
 * biệt có chủ đích so với các section A–D vốn dài và phân tích sâu hơn.
 */

import type { TheoryQuestion } from "./types";

const NOAI_SG =
  "Hiệu chỉnh theo dạng và chủ đề của đề trắc nghiệm vòng sơ loại NOAI 2026 (AI Singapore) đã công bố công khai.";
const VOAI_SCOPE =
  "Hiệu chỉnh theo mô tả công khai về vòng sơ loại VOAI: trắc nghiệm trên máy, 180 phút, phạm vi theo Syllabus IOAI.";

export const sectionEQuestions: readonly TheoryQuestion[] = [
  /* ================= math-linear-algebra ================= */
  {
    id: "math-linear-algebra-01",
    syllabusId: "math-linear-algebra",
    difficulty: "recall",
    format: "single-choice",
    stem: "Nhân ma trận kích thước 3×2 với ma trận 2×4 cho kết quả kích thước nào?",
    choices: ["3×4", "2×2", "3×2", "Không nhân được"],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: giữ số hàng của ma trận trái và số cột của ma trận phải.",
      "Sai: 2 là chiều trong, nó bị triệt tiêu.",
      "Sai: đó là kích thước ma trận thứ nhất.",
      "Sai: nhân được vì số cột trái (2) bằng số hàng phải (2).",
    ],
    explanation: "Quy tắc: (m×n)·(n×p) = (m×p); chiều trong phải khớp và biến mất khỏi kết quả.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-linear-algebra-02",
    syllabusId: "math-linear-algebra",
    difficulty: "recall",
    format: "single-choice",
    stem: "Ma trận A có kích thước 2×3. Kích thước của Aᵀ (chuyển vị) là gì?",
    choices: ["2×3", "3×2", "3×3", "2×2"],
    answerIndex: 1,
    choiceNotes: [
      "Sai: chuyển vị đổi chỗ hai chiều.",
      "Đúng: hàng thành cột, cột thành hàng.",
      "Sai: chuyển vị không làm ma trận vuông.",
      "Sai: không phải kết quả của phép chuyển vị.",
    ],
    explanation: "Chuyển vị đảo hai chiều: (m×n)ᵀ = (n×m). Phần tử tại (i, j) chuyển sang vị trí (j, i).",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-linear-algebra-03",
    syllabusId: "math-linear-algebra",
    difficulty: "recall",
    format: "single-choice",
    stem: "Ma trận đơn vị I có tính chất nào?",
    choices: [
      "Mọi phần tử đều bằng 1.",
      "Các phần tử trên đường chéo chính bằng 1, các phần tử còn lại bằng 0.",
      "Mọi phần tử đều bằng 0.",
      "Mọi phần tử trên đường chéo chính bằng 0.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: đó là ma trận toàn 1, không phải ma trận đơn vị.",
      "Đúng: nhờ đó AI = IA = A với mọi A có kích thước phù hợp.",
      "Sai: đó là ma trận không.",
      "Sai: ngược với định nghĩa.",
    ],
    explanation: "Ma trận đơn vị đóng vai trò số 1 trong phép nhân ma trận, và xuất hiện trong công thức ridge `(XᵀX + λI)`.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-linear-algebra-04",
    syllabusId: "math-linear-algebra",
    difficulty: "recall",
    format: "single-choice",
    stem: "Ma trận nào sau đây là ma trận đối xứng?",
    choices: ["[[1, 2], [3, 4]]", "[[1, 2], [2, 3]]", "[[0, 1], [0, 0]]", "[[1, 0], [1, 0]]"],
    answerIndex: 1,
    choiceNotes: [
      "Sai: phần tử (1,2) = 2 nhưng (2,1) = 3.",
      "Đúng: A = Aᵀ vì phần tử (1,2) và (2,1) đều bằng 2.",
      "Sai: (1,2) = 1 nhưng (2,1) = 0.",
      "Sai: (1,2) = 0 nhưng (2,1) = 1.",
    ],
    explanation: "Ma trận đối xứng thoả A = Aᵀ. Ma trận hiệp phương sai luôn đối xứng — đây là lý do PCA phân tích riêng được nó với trị riêng thực.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-linear-algebra-05",
    syllabusId: "math-linear-algebra",
    difficulty: "understand",
    format: "single-choice",
    stem: "Điều kiện để nhân được hai ma trận A và B (theo thứ tự AB) là gì?",
    choices: [
      "A và B phải cùng kích thước.",
      "Số cột của A bằng số hàng của B.",
      "Số hàng của A bằng số hàng của B.",
      "Cả hai phải là ma trận vuông.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: đó là điều kiện cho phép cộng ma trận.",
      "Đúng: chiều trong phải khớp.",
      "Sai: số hàng không phải điều kiện.",
      "Sai: ma trận chữ nhật vẫn nhân được.",
    ],
    explanation: "Đây là nguồn gốc của phần lớn lỗi shape khi lập trình mạng nơ-ron: chỉ cần chiều trong lệch là phép nhân thất bại.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-linear-algebra-06",
    syllabusId: "math-linear-algebra",
    difficulty: "understand",
    format: "single-choice",
    stem: "Phép nhân ma trận có tính giao hoán không?",
    choices: [
      "Có, AB luôn bằng BA.",
      "Không: nói chung AB ≠ BA, thậm chí BA có thể không xác định.",
      "Có, nếu cả hai ma trận cùng kích thước.",
      "Có, nếu cả hai đều đối xứng.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: đây là nhầm lẫn phổ biến do quen với số thực.",
      "Đúng: với A là 2×3 và B là 3×2, AB là 2×2 còn BA là 3×3.",
      "Sai: cùng kích thước vẫn không bảo đảm giao hoán.",
      "Sai: tích hai ma trận đối xứng nói chung không giao hoán.",
    ],
    explanation: "Không giao hoán nghĩa là thứ tự các lớp trong mạng có ý nghĩa: đổi thứ tự hai phép biến đổi tuyến tính cho kết quả khác.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-linear-algebra-07",
    syllabusId: "math-linear-algebra",
    difficulty: "understand",
    format: "single-choice",
    stem: "Trong PCA, các vector riêng của ma trận hiệp phương sai biểu diễn điều gì?",
    choices: [
      "Các hướng chính mà dữ liệu biến thiên mạnh nhất.",
      "Giá trị trung bình của từng đặc trưng.",
      "Nhãn của từng mẫu dữ liệu.",
      "Số lượng mẫu trong mỗi cụm.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: trị riêng đi kèm cho biết lượng phương sai theo hướng đó.",
      "Sai: trung bình được trừ đi trước khi tính hiệp phương sai.",
      "Sai: PCA không dùng nhãn.",
      "Sai: PCA không phân cụm.",
    ],
    explanation: "Cặp (vector riêng, trị riêng) chính là (hướng, lượng phương sai). Sắp trị riêng giảm dần sẽ cho thứ tự các thành phần chính.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-linear-algebra-08",
    syllabusId: "math-linear-algebra",
    difficulty: "apply",
    format: "numeric",
    stem: "Tính tích vô hướng của hai vector [1, 2, 3] và [4, 5, 6].",
    answer: 32,
    tolerance: 0,
    calculation: ["1×4 = 4; 2×5 = 10; 3×6 = 18.", "Tổng: 4 + 10 + 18 = 32."],
    explanation: "Tích vô hướng nhân từng cặp thành phần tương ứng rồi cộng lại. Đây là phép toán nền của mọi lớp Linear và của attention.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-linear-algebra-09",
    syllabusId: "math-linear-algebra",
    difficulty: "apply",
    format: "numeric",
    stem: "Vector v = [3, 4]. Tính chuẩn L2 (độ dài Euclid) của v.",
    answer: 5,
    tolerance: 0.001,
    calculation: ["‖v‖₂ = √(3² + 4²).", "= √(9 + 16) = √25 = 5."],
    explanation: "Chuẩn L2 là độ dài hình học của vector. Lưu ý cosine similarity đã tự chia cho tích hai chuẩn nên **không bắt buộc** chuẩn hoá trước; việc chuẩn hoá sẵn chỉ hữu ích khi muốn thay cosine bằng dot product cho rẻ, hoặc khi lập chỉ mục truy vấn vector.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-linear-algebra-10",
    syllabusId: "math-linear-algebra",
    difficulty: "apply",
    format: "numeric",
    stem: "Tính định thức của ma trận [[1, 2], [3, 4]].",
    answer: -2,
    tolerance: 0.001,
    calculation: ["Với ma trận 2×2 [[a, b], [c, d]]: det = ad − bc.", "= 1×4 − 2×3 = 4 − 6 = −2."],
    explanation: "Định thức khác 0 nghĩa là ma trận khả nghịch. Khi det(XᵀX) = 0, ma trận suy biến nên **công thức nghịch đảo** `(XᵀX)⁻¹Xᵀy` không dùng được và nghiệm không còn duy nhất — nhưng bài toán bình phương tối thiểu vẫn *có* nghiệm; ta lấy một nghiệm qua giả nghịch đảo hoặc thêm regularization.",
    calibratedFrom: NOAI_SG,
  },

  /* ================= math-calculus ================= */
  {
    id: "math-calculus-01",
    syllabusId: "math-calculus",
    difficulty: "recall",
    format: "numeric",
    stem: "Tính đạo hàm của f(x) = 5x + 3.",
    answer: 5,
    tolerance: 0,
    calculation: ["Đạo hàm của 5x là 5.", "Đạo hàm của hằng số 3 là 0.", "f′(x) = 5."],
    explanation: "Hàm bậc nhất có đạo hàm là hằng số, đúng bằng hệ số góc. Đây cũng là lý do gradient của mô hình tuyến tính không phụ thuộc giá trị x hiện tại.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-calculus-02",
    syllabusId: "math-calculus",
    difficulty: "recall",
    format: "single-choice",
    stem: "Gradient của một hàm nhiều biến là gì?",
    choices: [
      "Vector gồm các đạo hàm riêng theo từng biến.",
      "Một số vô hướng bằng tổng các đạo hàm riêng.",
      "Ma trận các đạo hàm cấp hai.",
      "Giá trị lớn nhất của hàm.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: ∇f = [∂f/∂x₁, ∂f/∂x₂, …].",
      "Sai: gradient là vector, không phải vô hướng.",
      "Sai: đó là ma trận Hessian.",
      "Sai: gradient là thông tin cục bộ về hướng.",
    ],
    explanation: "Gradient có cùng số chiều với tham số. Với mạng nơ-ron hàng triệu tham số, gradient là vector hàng triệu chiều.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-calculus-03",
    syllabusId: "math-calculus",
    difficulty: "recall",
    format: "single-choice",
    stem: "Trong vi phân tự động (automatic differentiation), computational graph là gì?",
    choices: [
      "Đồ thị ghi lại các phép toán và quan hệ phụ thuộc giữa chúng trong lượt tính xuôi, để lượt ngược áp dụng quy tắc chuỗi theo đúng thứ tự.",
      "Biểu đồ vẽ giá trị loss theo epoch.",
      "Sơ đồ kiến trúc mạng do người dùng vẽ tay.",
      "Đồ thị biểu diễn quan hệ giữa các mẫu dữ liệu.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: mỗi nút là một phép toán, mỗi cạnh là một phụ thuộc dữ liệu.",
      "Sai: đó là đường cong huấn luyện.",
      "Sai: đây là cấu trúc do framework tự dựng lúc chạy.",
      "Sai: nó ghi phép toán chứ không ghi quan hệ giữa mẫu.",
    ],
    explanation: "PyTorch dựng đồ thị này động khi chạy lượt xuôi; `loss.backward()` duyệt ngược đồ thị để tích luỹ gradient vào `.grad` của từng tensor lá.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-calculus-04",
    syllabusId: "math-calculus",
    difficulty: "understand",
    format: "single-choice",
    stem: "Quy tắc chuỗi phát biểu thế nào cho hàm hợp y = f(g(x))?",
    choices: ["dy/dx = f′(g(x))·g′(x)", "dy/dx = f′(x)·g′(x)", "dy/dx = f′(g′(x))", "dy/dx = f′(x) + g′(x)"],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: đạo hàm ngoài tính tại điểm g(x), nhân với đạo hàm trong.",
      "Sai: f′ phải được tính tại g(x), không phải tại x.",
      "Sai: không phải phép hợp của hai đạo hàm.",
      "Sai: đó là đạo hàm của tổng, không phải của hàm hợp.",
    ],
    explanation: "Đây là toàn bộ cơ sở toán học của backpropagation: gradient được nhân dồn từ lớp cuối về lớp đầu qua từng đạo hàm cục bộ.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-calculus-05",
    syllabusId: "math-calculus",
    difficulty: "understand",
    format: "single-choice",
    stem: "Đạo hàm riêng ∂f/∂x của hàm hai biến f(x, y) được tính thế nào?",
    choices: [
      "Lấy đạo hàm theo x và coi y như hằng số.",
      "Lấy đạo hàm theo cả x và y rồi cộng lại.",
      "Lấy đạo hàm theo y và coi x như hằng số.",
      "Lấy trung bình đạo hàm theo hai biến.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: đó là định nghĩa của đạo hàm riêng.",
      "Sai: đó là đạo hàm theo hướng đặc biệt, không phải đạo hàm riêng.",
      "Sai: đó là ∂f/∂y.",
      "Sai: không có phép lấy trung bình ở đây.",
    ],
    explanation: "Đạo hàm riêng cho biết loss đổi bao nhiêu khi chỉ một tham số thay đổi — chính là thông tin cần để cập nhật riêng tham số đó.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-calculus-06",
    syllabusId: "math-calculus",
    difficulty: "understand",
    format: "single-choice",
    stem: "Tại một điểm cực tiểu địa phương của hàm khả vi, gradient có giá trị thế nào?",
    choices: ["Bằng vector 0", "Bằng 1", "Luôn dương", "Không xác định"],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: mọi đạo hàm riêng đều triệt tiêu tại điểm dừng.",
      "Sai: không có lý do nào để gradient bằng 1.",
      "Sai: gradient dương nghĩa là hàm còn đang tăng theo hướng đó.",
      "Sai: hàm khả vi có gradient xác định ở mọi điểm.",
    ],
    explanation: "Lưu ý điều ngược lại không đúng: gradient bằng 0 cũng xảy ra ở cực đại và ở điểm yên ngựa — chính điểm yên ngựa mới là trở ngại chính trong học sâu.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-calculus-07",
    syllabusId: "math-calculus",
    difficulty: "apply",
    format: "numeric",
    stem: "Cho f(x) = x³. Tính f′(2).",
    answer: 12,
    tolerance: 0.001,
    calculation: ["f′(x) = 3x².", "f′(2) = 3 × 2² = 3 × 4 = 12."],
    explanation: "Quy tắc luỹ thừa: đạo hàm của xⁿ là n·xⁿ⁻¹.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-calculus-08",
    syllabusId: "math-calculus",
    difficulty: "apply",
    format: "numeric",
    stem: "Cho f(x, y) = x²y. Tính ∂f/∂x tại điểm (x, y) = (2, 3).",
    answer: 12,
    tolerance: 0.001,
    calculation: ["Coi y là hằng số: ∂f/∂x = 2xy.", "Tại (2, 3): 2 × 2 × 3 = 12."],
    explanation: "Đối chiếu: ∂f/∂y = x² = 4 tại cùng điểm. Gradient tại (2, 3) là vector [12, 4].",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-calculus-09",
    syllabusId: "math-calculus",
    difficulty: "apply",
    format: "numeric",
    stem: "Đạo hàm của ReLU(x) = max(0, x) tại x = −2 bằng bao nhiêu?",
    answer: 0,
    tolerance: 0,
    calculation: ["Với x < 0, ReLU(x) = 0 là hàm hằng.", "Đạo hàm của hàm hằng bằng 0."],
    explanation: "Đạo hàm bằng 0 ở nhánh âm chính là cơ chế gây hiện tượng dying ReLU: nơ-ron rơi hẳn vào vùng âm sẽ không còn nhận được tín hiệu học.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-calculus-10",
    syllabusId: "math-calculus",
    difficulty: "advanced",
    format: "single-choice",
    stem: "ReLU không khả vi tại x = 0. Vì sao điều đó không cản trở việc huấn luyện bằng gradient descent?",
    choices: [
      "Vì các framework thay ReLU bằng một hàm khác khi huấn luyện.",
      "Vì tập điểm không khả vi có độ đo 0 nên hầu như không bao giờ gặp đúng x = 0 với số thực dấu phẩy động; ngoài ra framework chỉ cần chọn một subgradient (thường là 0) tại điểm đó.",
      "Vì gradient descent không cần đạo hàm.",
      "Vì ReLU thực ra khả vi tại mọi điểm.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: ReLU được dùng nguyên dạng.",
      "Đúng: nêu đúng cả lý do xác suất lẫn cách xử lý kỹ thuật.",
      "Sai: gradient descent hoàn toàn dựa vào đạo hàm.",
      "Sai: tại 0, đạo hàm trái bằng 0 còn đạo hàm phải bằng 1.",
    ],
    trap: "Bẫy là kết luận “không khả vi ⇒ không dùng được”. Trong tối ưu thực hành, khả vi hầu khắp kèm subgradient là đủ.",
    explanation: "Cùng lập luận này áp dụng cho MAE (không khả vi tại 0) và cho max pooling — cả hai đều được dùng rộng rãi mà không gặp vấn đề.",
    calibratedFrom: NOAI_SG,
  },

  /* ================= math-probability ================= */
  {
    id: "math-probability-01",
    syllabusId: "math-probability",
    difficulty: "recall",
    format: "single-choice",
    stem: "Tổng xác suất của tất cả kết quả có thể trong một không gian mẫu bằng bao nhiêu?",
    choices: ["0", "1", "100", "Phụ thuộc số kết quả"],
    answerIndex: 1,
    choiceNotes: [
      "Sai: 0 là xác suất của biến cố không thể.",
      "Đúng: đây là tiên đề chuẩn hoá của xác suất.",
      "Sai: 100 là cách biểu diễn theo phần trăm, không phải giá trị xác suất.",
      "Sai: tổng luôn bằng 1 bất kể số kết quả.",
    ],
    explanation: "Chính tiên đề này khiến softmax phải chia cho tổng: đầu ra mới tạo thành một phân phối xác suất hợp lệ.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-probability-02",
    syllabusId: "math-probability",
    difficulty: "recall",
    format: "single-choice",
    stem: "Hai biến cố A và B độc lập khi nào?",
    choices: [
      "Khi P(A ∩ B) = P(A)·P(B).",
      "Khi P(A ∩ B) = 0.",
      "Khi P(A) = P(B).",
      "Khi P(A) + P(B) = 1.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: đây là định nghĩa của độc lập.",
      "Sai: đó là hai biến cố xung khắc — nói chung *không* độc lập.",
      "Sai: bằng nhau về xác suất không liên quan tới độc lập.",
      "Sai: đó là quan hệ bù nhau.",
    ],
    explanation: "Phân biệt xung khắc với độc lập là điểm hay nhầm: hai biến cố xung khắc có xác suất khác 0 thì chắc chắn *phụ thuộc*, vì biết A xảy ra là biết chắc B không xảy ra.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-probability-03",
    syllabusId: "math-probability",
    difficulty: "recall",
    format: "single-choice",
    stem: "Phương sai của một biến ngẫu nhiên đo điều gì?",
    choices: [
      "Giá trị trung bình của biến.",
      "Mức phân tán của các giá trị quanh giá trị kỳ vọng.",
      "Giá trị lớn nhất mà biến có thể nhận.",
      "Số lượng giá trị khác nhau mà biến có thể nhận.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: đó là kỳ vọng.",
      "Đúng: Var(X) = E[(X − E[X])²].",
      "Sai: đó là giá trị cực đại.",
      "Sai: đó là kích thước miền giá trị.",
    ],
    explanation: "Độ lệch chuẩn là căn bậc hai của phương sai và có cùng đơn vị với biến, nên thường dễ diễn giải hơn.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-probability-04",
    syllabusId: "math-probability",
    difficulty: "understand",
    format: "single-choice",
    stem: "Định lý Bayes cho phép tính gì?",
    choices: [
      "Đảo chiều xác suất có điều kiện: từ P(B|A) suy ra P(A|B) khi biết P(A) và P(B).",
      "Xác suất của hai biến cố độc lập cùng xảy ra.",
      "Giá trị kỳ vọng của một biến ngẫu nhiên.",
      "Phương sai của tổng hai biến ngẫu nhiên.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: P(A|B) = P(B|A)·P(A)/P(B).",
      "Sai: đó là quy tắc nhân cho biến cố độc lập.",
      "Sai: kỳ vọng tính theo công thức khác.",
      "Sai: không liên quan.",
    ],
    explanation: "Bayes là cách cập nhật niềm tin khi có bằng chứng mới: xác suất tiên nghiệm P(A) được nhân với hệ số hợp lý rồi chuẩn hoá lại.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-probability-05",
    syllabusId: "math-probability",
    difficulty: "understand",
    format: "single-choice",
    stem: "Dữ liệu thu nhập có vài giá trị cực lớn. Thống kê nào mô tả “giá trị điển hình” tốt hơn?",
    choices: [
      "Trung bình cộng, vì nó dùng toàn bộ dữ liệu.",
      "Trung vị, vì nó bền với giá trị ngoại lai.",
      "Giá trị lớn nhất.",
      "Phương sai.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: trung bình bị vài giá trị cực lớn kéo lệch mạnh.",
      "Đúng: trung vị chỉ phụ thuộc thứ hạng nên không bị đuôi phân phối chi phối.",
      "Sai: cực trị là thống kê nhạy cảm nhất với ngoại lai.",
      "Sai: phương sai đo độ phân tán, không đo giá trị điển hình.",
    ],
    explanation: "Cùng nguyên lý với việc chọn MAE thay MSE: thống kê dựa trên thứ hạng bền hơn thống kê dựa trên tổng bình phương.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-probability-06",
    syllabusId: "math-probability",
    difficulty: "understand",
    format: "single-choice",
    stem: "Entropy của một phân phối xác suất đo điều gì?",
    choices: [
      "Mức bất định trung bình của phân phối; đạt cực đại khi phân phối đều.",
      "Giá trị trung bình của biến ngẫu nhiên.",
      "Số lượng mẫu trong tập dữ liệu.",
      "Sai số của mô hình dự đoán.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: H = −Σ p·log p, lớn nhất khi mọi kết quả đồng khả năng.",
      "Sai: đó là kỳ vọng.",
      "Sai: entropy là tính chất của phân phối, không phải của cỡ mẫu.",
      "Sai: đó là loss hoặc chỉ số lỗi.",
    ],
    explanation: "Entropy nối liền hai chỗ trong lộ trình: tiêu chí chia của cây quyết định, và cross-entropy làm hàm mất mát cho phân loại.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-probability-07",
    syllabusId: "math-probability",
    difficulty: "apply",
    format: "numeric",
    stem: "Tung hai đồng xu cân đối. Xác suất cả hai đều ra mặt ngửa là bao nhiêu?",
    answer: 0.25,
    tolerance: 0.001,
    calculation: [
      "Hai lần tung độc lập, mỗi lần P(ngửa) = 0.5.",
      "P(cả hai ngửa) = 0.5 × 0.5 = 0.25.",
    ],
    explanation: "Không gian mẫu có 4 kết quả đồng khả năng {NN, NS, SN, SS}, trong đó đúng một kết quả thoả mãn.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-probability-08",
    syllabusId: "math-probability",
    difficulty: "apply",
    format: "numeric",
    stem: "Bệnh có tỷ lệ mắc 1%. Xét nghiệm phát hiện đúng 99% người mắc bệnh và cho dương tính giả ở 5% người không mắc. Một người xét nghiệm dương tính; xác suất người đó thực sự mắc bệnh là bao nhiêu? (làm tròn 3 chữ số)",
    answer: 0.167,
    tolerance: 0.005,
    calculation: [
      "P(D)·P(+|D) = 0.01 × 0.99 = 0.0099.",
      "P(¬D)·P(+|¬D) = 0.99 × 0.05 = 0.0495.",
      "P(+) = 0.0099 + 0.0495 = 0.0594.",
      "P(D|+) = 0.0099 / 0.0594 ≈ 0.167.",
    ],
    explanation: "Dù xét nghiệm “chính xác 99%”, khả năng thực sự mắc bệnh khi dương tính chỉ khoảng 17%, vì nhóm không mắc bệnh đông hơn gấp 99 lần.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-probability-09",
    syllabusId: "math-probability",
    difficulty: "apply",
    format: "numeric",
    stem: "Cho dãy số [2, 4, 4, 4, 5, 5, 7, 9]. Tính độ lệch chuẩn của tổng thể (chia cho n).",
    answer: 2,
    tolerance: 0.01,
    calculation: [
      "Trung bình = 40/8 = 5.",
      "Bình phương độ lệch: 9, 1, 1, 1, 0, 0, 4, 16 → tổng = 32.",
      "Phương sai = 32/8 = 4; độ lệch chuẩn = √4 = 2.",
    ],
    explanation: "Lưu ý phân biệt chia cho n (tổng thể) với chia cho n−1 (mẫu). NumPy mặc định `ddof=0` (chia n), còn pandas mặc định `ddof=1` (chia n−1).",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "math-probability-10",
    syllabusId: "math-probability",
    difficulty: "advanced",
    format: "single-choice",
    stem: "Vì sao xét nghiệm “chính xác 99%” lại cho xác suất mắc bệnh khi dương tính chỉ khoảng 17%?",
    choices: [
      "Vì xét nghiệm bị lỗi kỹ thuật.",
      "Vì tỷ lệ mắc bệnh nền rất thấp: nhóm không mắc bệnh đông hơn nhiều, nên dù tỷ lệ dương tính giả nhỏ, số dương tính giả tuyệt đối vẫn vượt xa số dương tính thật.",
      "Vì mẫu xét nghiệm quá nhỏ.",
      "Vì độ nhạy và độ đặc hiệu không được đo đúng.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: các con số đã cho là hiệu năng đúng của xét nghiệm.",
      "Đúng: đây là nguỵ biện tỷ lệ nền (base rate fallacy).",
      "Sai: kết quả này không phụ thuộc cỡ mẫu.",
      "Sai: chúng được cho tường minh trong đề.",
    ],
    trap: "Bẫy là chuyển thẳng “độ chính xác 99%” thành “99% khả năng mắc bệnh”. Đây là hai đại lượng có điều kiện ngược chiều nhau: P(+|D) khác hẳn P(D|+).",
    explanation: "Đây chính là nền tảng xác suất của bài toán lớp hiếm trong học máy: với 1% mẫu dương, precision thấp là điều phải dự kiến chứ không phải dấu hiệu mô hình hỏng. Xem thêm [confusion-roc-05].",
    calibratedFrom: NOAI_SG,
  },

  /* ================= computing-python ================= */
  {
    id: "computing-python-01",
    syllabusId: "computing-python",
    difficulty: "recall",
    format: "single-choice",
    stem: "Khác biệt giữa toán tử `is` và `==` trong Python là gì?",
    choices: [
      "`is` so sánh danh tính đối tượng (cùng một vùng nhớ); `==` so sánh giá trị.",
      "`is` so sánh giá trị; `==` so sánh kiểu dữ liệu.",
      "Hai toán tử hoàn toàn tương đương.",
      "`is` chỉ dùng cho số, `==` chỉ dùng cho chuỗi.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: `is` hỏi “có phải cùng một đối tượng không”, `==` hỏi “có bằng nhau không”.",
      "Sai: đảo ngược, và `==` không so sánh kiểu.",
      "Sai: chúng khác nhau về ngữ nghĩa.",
      "Sai: cả hai dùng được cho mọi kiểu.",
    ],
    explanation: "Quy ước thực hành: dùng `is` cho `None`, `True`, `False`; dùng `==` cho mọi so sánh giá trị khác.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "computing-python-02",
    syllabusId: "computing-python",
    difficulty: "recall",
    format: "single-choice",
    stem: "Độ phức tạp trung bình của việc truy cập phần tử theo chỉ số `a[i]` trên `list` Python là gì?",
    choices: ["O(1)", "O(log n)", "O(n)", "O(n log n)"],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: list là mảng động, truy cập theo chỉ số là phép tính địa chỉ trực tiếp.",
      "Sai: đó là tìm kiếm nhị phân trên mảng đã sắp.",
      "Sai: O(n) là chi phí của toán tử `in` trên list.",
      "Sai: đó là chi phí sắp xếp.",
    ],
    explanation: "Đối chiếu: `append` là O(1) khấu hao, còn `insert(0, x)` là O(n) vì phải dịch toàn bộ phần tử phía sau.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "computing-python-03",
    syllabusId: "computing-python",
    difficulty: "recall",
    format: "single-choice",
    stem: "Vectorisation trong NumPy nghĩa là gì?",
    choices: [
      "Thay vòng lặp Python bằng các phép toán trên toàn mảng, được thực thi bởi mã biên dịch sẵn ở tầng dưới.",
      "Chuyển ma trận thành vector một chiều.",
      "Tăng số chiều của mảng.",
      "Chia mảng thành nhiều phần để xử lý song song bằng nhiều tiến trình.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: nhờ đó tránh được chi phí thông dịch của vòng lặp Python.",
      "Sai: đó là `ravel`/`flatten`.",
      "Sai: đó là `expand_dims`.",
      "Sai: đó là xử lý đa tiến trình, khái niệm khác.",
    ],
    explanation: "Chênh lệch tốc độ thường là hàng chục tới hàng trăm lần. Đây là lý do quy tắc “tránh vòng lặp Python trên mảng NumPy” được nhắc đi nhắc lại.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "computing-python-04",
    syllabusId: "computing-python",
    difficulty: "understand",
    format: "single-choice",
    stem: "Kiểm tra `x in collection`: độ phức tạp trung bình khác nhau thế nào giữa `list` và `set`?",
    choices: [
      "list là O(n), set là O(1) trung bình nhờ bảng băm.",
      "Cả hai đều là O(1).",
      "Cả hai đều là O(n).",
      "list là O(1), set là O(n).",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: list phải duyệt tuần tự, set tra trực tiếp qua giá trị băm.",
      "Sai: list không có chỉ mục theo giá trị.",
      "Sai: set nhanh hơn hẳn.",
      "Sai: đảo ngược hoàn toàn.",
    ],
    explanation: "Hệ quả thực dụng: đổi `list` thành `set` cho các phép kiểm tra thành viên lặp lại có thể biến thuật toán O(n²) thành O(n).",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "computing-python-05",
    syllabusId: "computing-python",
    difficulty: "understand",
    format: "single-choice",
    stem: "Ưu điểm chính của generator so với việc trả về một list đầy đủ là gì?",
    choices: [
      "Sinh phần tử theo yêu cầu nên chỉ giữ một phần tử tại một thời điểm, tiết kiệm bộ nhớ với dữ liệu rất lớn.",
      "Luôn chạy nhanh hơn list về tổng thời gian.",
      "Cho phép truy cập ngẫu nhiên theo chỉ số.",
      "Tự động sắp xếp các phần tử.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: đây là ý nghĩa của tính “lười” (lazy evaluation).",
      "Sai: tổng thời gian có thể tương đương hoặc chậm hơn đôi chút.",
      "Sai: generator không hỗ trợ lập chỉ mục.",
      "Sai: generator không sắp xếp.",
    ],
    explanation: "Đây chính là mô hình mà `DataLoader` dùng: dữ liệu được nạp theo từng batch thay vì tải toàn bộ tập vào RAM.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "computing-python-06",
    syllabusId: "computing-python",
    difficulty: "understand",
    format: "single-choice",
    stem: "Biểu thức `a[::2]` trên một list trả về gì?",
    choices: [
      "Các phần tử ở vị trí chẵn (bước nhảy 2 từ đầu đến cuối).",
      "Hai phần tử đầu tiên.",
      "List đảo ngược.",
      "Các phần tử ở vị trí lẻ.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: cú pháp là `[bắt_đầu:kết_thúc:bước]`, ở đây bước bằng 2.",
      "Sai: đó là `a[:2]`.",
      "Sai: đảo ngược là `a[::-1]`.",
      "Sai: vị trí lẻ là `a[1::2]`.",
    ],
    explanation: "Slicing với bước âm rất hay bị nhầm: `a[::-1]` đảo ngược toàn bộ, còn `a[::-2]` lấy cách một phần tử tính từ cuối về đầu.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "computing-python-07",
    syllabusId: "computing-python",
    difficulty: "apply",
    format: "numeric",
    stem: "`len([x for x in range(10) if x % 3 == 0])` bằng bao nhiêu?",
    answer: 4,
    tolerance: 0,
    calculation: [
      "`range(10)` cho 0..9.",
      "Các số chia hết cho 3: 0, 3, 6, 9.",
      "Số phần tử: 4.",
    ],
    explanation: "Lưu ý 0 chia hết cho 3 nên được tính — bỏ sót số 0 là lỗi đếm thường gặp nhất ở dạng câu này.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "computing-python-08",
    syllabusId: "computing-python",
    difficulty: "apply",
    format: "numeric",
    stem: "Đoạn mã `for i in range(5): for j in range(i): count += 1` làm `count` tăng tổng cộng bao nhiêu lần?",
    answer: 10,
    tolerance: 0,
    calculation: [
      "Vòng trong chạy i lần với i = 0, 1, 2, 3, 4.",
      "Tổng: 0 + 1 + 2 + 3 + 4 = 10.",
    ],
    explanation: "Tổng quát, cấu trúc này chạy n(n−1)/2 lần, tức độ phức tạp O(n²) — dạng vòng lặp lồng kinh điển khi phân tích thuật toán.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "computing-python-09",
    syllabusId: "computing-python",
    difficulty: "apply",
    format: "single-choice",
    stem: "Thuật toán O(n²) xử lý n = 100.000 phần tử. Vì sao nó thường không khả thi trong khi O(n log n) thì được?",
    choices: [
      "Vì O(n²) cần nhiều bộ nhớ hơn.",
      "Vì n² = 10¹⁰ phép tính, lớn hơn gần bốn bậc độ lớn so với n·log₂n ≈ 1.7 × 10⁶.",
      "Vì O(n²) không chạy được trên máy 64-bit.",
      "Vì O(n log n) luôn dùng ít bộ nhớ hơn.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: độ phức tạp ở đây nói về thời gian, không phải bộ nhớ.",
      "Đúng: 10¹⁰ / (1.7 × 10⁶) ≈ 5.9 × 10³, tức khoảng 3.8 bậc độ lớn — gần sáu nghìn lần.",
      "Sai: không có giới hạn kiến trúc nào như vậy.",
      "Sai: hai khái niệm độc lập nhau.",
    ],
    explanation: "Thói quen cần rèn: quy đổi độ phức tạp thành số phép tính ước lượng trước khi chạy. Máy tính phổ thông xử lý cỡ 10⁸–10⁹ phép đơn giản mỗi giây.",
    calibratedFrom: VOAI_SCOPE,
  },
  {
    id: "computing-python-10",
    syllabusId: "computing-python",
    difficulty: "advanced",
    format: "single-choice",
    stem: "Đang gỡ lỗi một pipeline học máy cho kết quả kém bất thường. Cách tiếp cận hiệu quả nhất là gì?",
    choices: [
      "Đổi đồng thời nhiều thứ (mô hình, learning rate, augmentation) để nhanh chóng tìm ra cấu hình tốt.",
      "Đặt giả thuyết cụ thể, kiểm chứng từng giả thuyết bằng một thay đổi nhỏ nhất có thể, cố định seed và so sánh với một baseline đã biết.",
      "Tăng số epoch lên gấp mười rồi chờ kết quả.",
      "Viết lại toàn bộ pipeline từ đầu.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: đổi nhiều biến cùng lúc khiến không quy được kết quả cho nguyên nhân nào.",
      "Đúng: cô lập biến và có baseline là hai điều kiện để suy luận nhân quả.",
      "Sai: đây là chờ đợi chứ không phải chẩn đoán.",
      "Sai: tốn kém và thường tái tạo lại đúng lỗi cũ.",
    ],
    trap: "Bẫy là “dò càng nhanh càng tốt”. Trong một hệ thống nhiều thành phần, tốc độ đến từ việc loại trừ nguyên nhân có hệ thống, không đến từ việc thử nhiều cấu hình.",
    explanation: "Trình tự chẩn đoán chuẩn: kiểm tra dữ liệu và nhãn trước, thử overfit một batch nhỏ, xác nhận pipeline đánh giá đúng, rồi mới bàn tới mô hình và siêu tham số.",
    calibratedFrom: VOAI_SCOPE,
  },

  /* ================= genai ================= */
  {
    id: "genai-01",
    syllabusId: "genai",
    difficulty: "recall",
    format: "single-choice",
    stem: "Token trong mô hình ngôn ngữ là gì?",
    choices: [
      "Đơn vị văn bản nhỏ nhất mà mô hình xử lý — thường là một từ, một phần từ (subword) hoặc một ký tự.",
      "Một tham số học được của mô hình.",
      "Một câu hoàn chỉnh trong dữ liệu huấn luyện.",
      "Mã xác thực để gọi API.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: văn bản được tokenizer cắt thành chuỗi token trước khi đưa vào mô hình.",
      "Sai: tham số là trọng số của mô hình.",
      "Sai: một câu thường gồm nhiều token.",
      "Sai: đó là API token, trùng tên nhưng khác nghĩa hoàn toàn.",
    ],
    explanation: "Vì chi phí và giới hạn ngữ cảnh đều tính theo token, ước lượng số token là kỹ năng thực dụng: tiếng Anh trung bình khoảng 4 ký tự một token.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "genai-02",
    syllabusId: "genai",
    difficulty: "recall",
    format: "single-choice",
    stem: "Context window của một mô hình ngôn ngữ là gì?",
    choices: [
      "Số token tối đa mà mô hình có thể xử lý trong một lượt, gồm cả prompt lẫn phần sinh ra.",
      "Khoảng thời gian mô hình ghi nhớ người dùng.",
      "Số lượng mô hình chạy song song.",
      "Kích thước tập dữ liệu huấn luyện.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: vượt quá giới hạn thì phần đầu bị cắt hoặc yêu cầu bị từ chối.",
      "Sai: mô hình không tự ghi nhớ qua các phiên.",
      "Sai: đó là cấu hình phục vụ.",
      "Sai: đó là quy mô dữ liệu tiền huấn luyện.",
    ],
    explanation: "Giới hạn này bắt nguồn từ chi phí attention bậc hai theo độ dài chuỗi, và là lý do tồn tại của RAG cùng các kỹ thuật chia đoạn tài liệu.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "genai-03",
    syllabusId: "genai",
    difficulty: "recall",
    format: "single-choice",
    stem: "Thiên lệch (bias) trong hệ thống AI chủ yếu bắt nguồn từ đâu?",
    choices: [
      "Từ dữ liệu huấn luyện phản ánh những thiên lệch sẵn có trong xã hội hoặc trong cách thu thập dữ liệu.",
      "Từ việc mô hình có quá nhiều tham số.",
      "Từ tốc độ GPU không đồng đều.",
      "Từ việc dùng ngôn ngữ lập trình Python.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: mô hình học đúng những quy luật có trong dữ liệu, kể cả quy luật không mong muốn.",
      "Sai: số tham số ảnh hưởng năng lực, không tạo ra thiên lệch xã hội.",
      "Sai: phần cứng không liên quan.",
      "Sai: ngôn ngữ lập trình không liên quan.",
    ],
    explanation: "Vì thế phần lớn công việc giảm thiểu thiên lệch nằm ở khâu dữ liệu và đánh giá, không nằm ở kiến trúc mô hình. Đạo đức AI là một mục trong Syllabus IOAI.",
    calibratedFrom: VOAI_SCOPE,
  },
  {
    id: "genai-04",
    syllabusId: "genai",
    difficulty: "understand",
    format: "single-choice",
    stem: "Khi nào nên finetune thay vì chỉ dùng prompting với một mô hình ngôn ngữ lớn?",
    choices: [
      "Khi cần mô hình bám một định dạng/phong cách đặc thù một cách ổn định trên khối lượng lớn, và đã có đủ dữ liệu ví dụ chất lượng.",
      "Bất cứ khi nào prompting cho kết quả chưa hoàn hảo ở lần thử đầu tiên.",
      "Khi cần mô hình biết thông tin mới cập nhật hằng ngày.",
      "Khi muốn giảm chi phí thử nghiệm ban đầu.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: finetune hiệu quả nhất cho *hành vi và định dạng*, khi quy mô đủ lớn để bù chi phí.",
      "Sai: nên cải thiện prompt và thử few-shot trước, vì rẻ hơn nhiều.",
      "Sai: kiến thức thay đổi thường xuyên thuộc về RAG, không thuộc finetune.",
      "Sai: finetune tốn kém hơn prompting ở giai đoạn thử nghiệm.",
    ],
    explanation: "Nguyên tắc chọn: cần *kiến thức* mới hoặc dẫn nguồn thì dùng RAG; cần *hành vi/định dạng* ổn định ở quy mô lớn thì finetune; còn lại ưu tiên prompting.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "genai-05",
    syllabusId: "genai",
    difficulty: "understand",
    format: "single-choice",
    stem: "Vector database phục vụ vai trò gì trong một hệ thống RAG?",
    choices: [
      "Lưu embedding của các đoạn tài liệu và tìm nhanh những đoạn có embedding gần nhất với embedding của câu hỏi.",
      "Lưu trọng số của mô hình ngôn ngữ.",
      "Lưu lịch sử hội thoại dưới dạng văn bản thuần.",
      "Huấn luyện lại mô hình sau mỗi truy vấn.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: đây là tìm kiếm ngữ nghĩa bằng láng giềng gần nhất trong không gian embedding.",
      "Sai: trọng số được lưu ở nơi khác.",
      "Sai: đó là bộ nhớ hội thoại thông thường.",
      "Sai: RAG không huấn luyện lại mô hình.",
    ],
    explanation: "Tìm kiếm ngữ nghĩa khớp theo *ý nghĩa* chứ không theo từ khoá, nên câu hỏi diễn đạt khác tài liệu vẫn truy hồi đúng đoạn liên quan.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "genai-06",
    syllabusId: "genai",
    difficulty: "understand",
    format: "single-choice",
    stem: "Rủi ro xã hội chính của công nghệ deepfake là gì?",
    choices: [
      "Tạo ra hình ảnh, giọng nói hoặc video giả mạo người thật rất thuyết phục, phục vụ lừa đảo, bôi nhọ và phát tán thông tin sai.",
      "Làm tăng dung lượng lưu trữ cần thiết cho video.",
      "Làm chậm tốc độ đường truyền internet.",
      "Khiến mô hình học sâu khó huấn luyện hơn.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: rủi ro nằm ở việc phá vỡ niềm tin vào bằng chứng nghe nhìn.",
      "Sai: đây là vấn đề kỹ thuật nhỏ, không phải rủi ro xã hội.",
      "Sai: không liên quan.",
      "Sai: không liên quan.",
    ],
    explanation: "Các hướng ứng phó gồm thuỷ vân số, chuẩn xác thực nguồn gốc nội dung, mô hình phát hiện, và giáo dục nhận thức truyền thông — không có giải pháp đơn lẻ nào đủ.",
    calibratedFrom: VOAI_SCOPE,
  },
  {
    id: "genai-07",
    syllabusId: "genai",
    difficulty: "understand",
    format: "single-choice",
    stem: "Chain-of-thought prompting là kỹ thuật gì?",
    choices: [
      "Yêu cầu mô hình trình bày các bước suy luận trung gian trước khi đưa ra đáp án, thường cải thiện kết quả ở bài toán nhiều bước.",
      "Nối nhiều mô hình khác nhau thành một chuỗi xử lý.",
      "Chia nhỏ tài liệu thành các đoạn để lập chỉ mục.",
      "Huấn luyện mô hình trên dữ liệu suy luận logic.",
    ],
    answerIndex: 0,
    choiceNotes: [
      "Đúng: cho mô hình “không gian” để tính toán từng bước thay vì đoán ngay đáp án.",
      "Sai: đó là pipeline hoặc chaining ở mức hệ thống.",
      "Sai: đó là chunking trong RAG.",
      "Sai: đó là huấn luyện, còn đây là kỹ thuật lúc suy luận.",
    ],
    explanation: "Cảnh báo quan trọng: chuỗi suy luận được viết ra không nhất thiết là quá trình tính toán thật bên trong mô hình, nên không được coi nó là lời giải thích đáng tin cậy.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "genai-08",
    syllabusId: "genai",
    difficulty: "apply",
    format: "single-choice",
    stem: "Cần đánh giá chất lượng của một hệ thống tóm tắt văn bản dùng LLM. Cách làm hợp lý nhất là gì?",
    choices: [
      "Chỉ dùng perplexity của mô hình.",
      "Kết hợp chỉ số tự động (ROUGE, BERTScore) với đánh giá của con người theo tiêu chí rõ ràng về tính trung thực, độ bao phủ và độ ngắn gọn.",
      "Đo tốc độ sinh token mỗi giây.",
      "Hỏi chính mô hình xem bản tóm tắt của nó có tốt không.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: perplexity không đo được chất lượng tóm tắt.",
      "Đúng: chỉ số tự động rẻ và lặp lại được, đánh giá người bắt được lỗi bịa đặt mà chỉ số tự động bỏ sót.",
      "Sai: đó là chỉ số vận hành.",
      "Sai: mô hình tự chấm mình có thiên lệch hệ thống, chỉ dùng như tín hiệu sơ bộ.",
    ],
    explanation: "Với tóm tắt, tiêu chí quan trọng nhất thường là tính trung thực với văn bản gốc — thứ mà ROUGE (chỉ đo trùng lặp n-gram) gần như không phát hiện được.",
    calibratedFrom: NOAI_SG,
  },
  {
    id: "genai-09",
    syllabusId: "genai",
    difficulty: "apply",
    format: "single-choice",
    stem: "Mô hình sinh ảnh được huấn luyện trên dữ liệu web tạo ra ảnh “bác sĩ” hầu hết là nam giới. Nhận định đúng nhất là gì?",
    choices: [
      "Đây là phản ánh khách quan của thực tế nên không cần can thiệp.",
      "Mô hình đang tái tạo và có thể khuếch đại thiên lệch trong dữ liệu huấn luyện; cần đo mức chênh lệch một cách định lượng và cân nhắc can thiệp ở dữ liệu, quá trình huấn luyện hoặc khâu tạo prompt.",
      "Đây là lỗi ngẫu nhiên, chạy lại nhiều lần sẽ hết.",
      "Chỉ cần tăng kích thước mô hình là tự khắc phục.",
    ],
    answerIndex: 1,
    choiceNotes: [
      "Sai: dữ liệu web không phải mẫu đại diện khách quan, và hệ thống triển khai rộng có thể củng cố định kiến.",
      "Đúng: nêu đúng cơ chế và các điểm can thiệp khả dĩ.",
      "Sai: đây là thiên lệch có hệ thống, không phải nhiễu ngẫu nhiên.",
      "Sai: mô hình lớn hơn thường học thiên lệch rõ hơn chứ không tự sửa.",
    ],
    explanation: "Bước đầu tiên luôn là *đo*: xác định thuộc tính cần quan tâm, lấy mẫu đủ lớn và báo cáo tỷ lệ. Không đo được thì mọi tuyên bố cải thiện đều không kiểm chứng được.",
    calibratedFrom: VOAI_SCOPE,
  },
  {
    id: "genai-10",
    syllabusId: "genai",
    difficulty: "advanced",
    format: "true-false-set",
    stem: "Xét việc sử dụng AI có trách nhiệm trong học tập và trong thi cử.",
    statements: [
      {
        text: "Một mô hình đạt độ chính xác tổng thể cao vẫn có thể hoạt động kém hơn hẳn trên một nhóm nhân khẩu cụ thể.",
        answer: true,
        note: "Chỉ số tổng hợp che giấu chênh lệch giữa các nhóm; vì thế cần báo cáo hiệu năng tách theo nhóm.",
      },
      {
        text: "Dùng AI để đối chiếu lập luận sau khi đã tự giải là cách dùng phù hợp với quy tắc SOLO-90/COACH-10 của lộ trình.",
        answer: true,
        note: "Ranh giới nằm ở chỗ bằng chứng tự làm phải có trước, và AI chỉ xác nhận đúng/sai hoặc nêu phản ví dụ.",
      },
      {
        text: "Nội dung do AI sinh ra có thể chứa thông tin sai nhưng được trình bày rất thuyết phục, nên phải kiểm chứng bằng nguồn độc lập trước khi sử dụng.",
        answer: true,
        note: "Độ trôi chảy của văn bản không tương quan với độ chính xác của nội dung.",
      },
      {
        text: "Vì mô hình được huấn luyện trên dữ liệu công khai nên mọi đầu ra của nó đều được tự do sử dụng mà không cần cân nhắc bản quyền hay ghi nguồn.",
        answer: false,
        note: "Tình trạng pháp lý của dữ liệu huấn luyện và của đầu ra là hai vấn đề khác nhau; quy định về bản quyền, giấy phép và liêm chính học thuật vẫn áp dụng.",
      },
    ],
    trap: "Ba ý đầu đúng nên ý (d) dễ bị chọn theo quán tính — đúng kiểu bẫy của dạng đúng/sai bốn ý. Nội dung của (d) cũng là hiểu lầm phổ biến nhất trong thực tế.",
    explanation:
      "Xem `docs/QUY_TAC_SOLO_90.md` và `docs/TAI_NGUYEN_HOP_PHAP.md`: quy tắc của dự án yêu cầu tự làm trước, dùng AI để đối chiếu, và luôn ghi rõ nguồn cùng giấy phép của mọi tài nguyên sử dụng.",
    calibratedFrom: VOAI_SCOPE,
  },
];
